### PR TITLE
Convert NodeJS load logic to UMD module format.

### PR DESCRIPTION
**Pull request by avishnyak**
This commit fixes an issues where the environment has a ```require``` function but is not a CommonJS implementation of ```require```.

The first commit in this PR contains the actual logic changes.  The second commit brings the PR in line with style requirements and jshint.

### CODE REVIEW

**Comment by tivie** [comment]
@avishnyak Thanks.

@SyntaxRules Can you have a look into this? Thanks!

**Comment by SyntaxRules** [comment]
Looks good thanks! 

Following semver, i think this requires a minor bump. (No breaking changes, yet no bug fixes either.) If everyone agrees, I'll release this as `1.1.0`.

**Comment by tivie** [comment]
sure, go ahead

**Comment by avishnyak** [comment]
Do you have any estimate on when you would be able to do the release and get it out on npm?

**Pull request merged**
