### PR TITLE
Replace element.

### PR DESCRIPTION
**Pull request by TeffenEllis**
This PR changes the directive to replace the element it's set on. 
This fixes issues surrounding CSS selectors targeting the immediate child elements.

### CODE REVIEW

**Comment by SyntaxRules** [comment]
It looks like the Travis CI checks need to be updated to the latest node.js for them to work. @tivie What version on node.js/npm are we supporting for release?

**Comment by tivie** [comment]
@SyntaxRules Showdown llibrary supports from 0.8 through 7.0.

**Comment by SyntaxRules** [comment]
@TeffenEllis can you rebase off master to get the travis CI build to work?

**Comment by TeffenEllis** [comment]
@SyntaxRules I no longer have commit access to that repo but I can make a new PR shortly.

**Pull request closed without merging**
